### ISSUE TITLE
Consider using node-sass 1.0.3

### ISSUE THREAD

**Issue by adam-beck** [dlmanning/gulp-sass#147]
The current version of node-sass does not compile source-maps correctly, which is a result of a bug in libsass. Would it be beneficial to move to an earlier version of node-sass (which would compile against an earlier version of libsass) in order to have source-maps working properly?

The issue in particular is #113

**Comment by aaronjensen** [comment]
@laurelnaiad it doesn't seem like test pass on your branch. The branch doesn't work in my project either (maybe because I'm using sourcemaps?)

```
/Users/aaronjensen/Source/gulp-sass/node_modules/tape/index.js:65
        throw err
              ^
TypeError: Cannot call method 'map' of undefined
    at opts.success (/Users/aaronjensen/Source/gulp-sass/index.js:54:43)
    at options.success (/Users/aaronjensen/Source/gulp-sass/node_modules/node-sass/lib/index.js:169:7)
npm ERR! Test failed.  See above for more details.
```

**Comment by laurelnaiad** [comment]
I'm not surprised the tests don't pass. I didn't make any effort to "finish the job" because node-sass version 2 is still beta.

That said, I'm using sourcemaps with my unfinished branch successfully (like so https://github.com/marklogic/marklogic-samplestack/blob/develop/browser/dev-tasks/build/buildSteps.js#L88).

I will take a look at the test situation., which may also yield something that doesn't trigger the problem you're having. 

I suspect the issue is that node-sass api changed, and I allowed that change to flow throw to gulp-sass' api in the success callback. I did that intentionally because I had to either (a) go against the grain/direction node-sass is heading or (b) let flow. I went with the latter realizing it's a breaking change, and I didn't update the tests.

If we assume that this is the problem you're having, then I suppose now is a good time and this is a reasonable place to discuss which way gulp-sass should go.

You can get glimpses of node-sass' new api in the examples (https://github.com/sass/node-sass#examples) and in a comment made by https://github.com/sass/node-sass/issues/517#issuecomment-68089798

In my branch, the locus of the issue is at https://github.com/laurelnaiad/gulp-sass/blob/ea10b260c3165f1de7a5b151be1a42bde20f9920/index.js#L45

So -- and I'll /cc @dlmanning here-- which way to go? Allow the new node-sass api to flow through to gulp-sass success callback? Or hide it behind a tranformation of those arguments to match what gulp-sass does today?

For what it's worth, I stand by my election to allow the change to propagate, but I don't fundamentally care that much, and am happy enough to go either way. Might as well decide soon, as I think node-sass v2 release is probably imminent. libsass 3.1.0 just went live and I think that's *one of* the last things that node-sass folks were waiting for...

P.S. I am also curious as to whether, with the changes to node-sass sourcemaps' support, some of the gulp-sass sourcemaps code might be unwound... something tells me that there is now a step that is no longer needed being performed....

**Comment by aaronjensen** [comment]
Ok, so one difference is that my project is using indented syntax. I had `sourceComments: 'normal'` and that errors, it also errors if change to `indentedSyntax: true`.

**Comment by laurelnaiad** [comment]
I think "normal" is the default, hence what I'm using.  indentedSyntax might be a node-sass v2 issue?

My prior comment was a bit under-informed, though. I don't think the API change I was referring to is the source of all of the problems, just one of them.

Most of the failing tests are due to an insignificant change in how node-sass is reporting errors.  However, there is more to the sourceMaps issues than I had realized. I'm playing with it now.

**Comment by aaronjensen** [comment]
Well, I'm not sure, the error was in gulp-sass. I haven't had a chance to dig into it:

```
/Users/aaronjensen/Source/schools-program/node_modules/gulp-sass/index.js:54
        obj.map.sources = obj.map.sources.map(function(source) {
                                          ^
TypeError: Cannot call method 'map' of undefined
  at opts.success (/Users/aaronjensen/Source/schools-program/node_modules/gulp-sass/index.js:54:43)
  at options.success (/Users/aaronjensen/Source/schools-program/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:169:7)
```

**Comment by laurelnaiad** [comment]
That one you mention is a relatively dumb bug of mine. I've got that one under control now.

The larger problem that remains as I toy with thisThe problems seem to center around this section, which has become notorious in my own world:

```
    if (opts.sourceComments === 'map' || opts.sourceComments === 'normal') {
      opts.sourceMap = opts.sourceMap || '';
      opts.file = file.path;
    } else {
      opts.data = file.contents.toString();
    }
```

I'm pretty sure the interaction between the gulp-sass and node-sass parameters has changed a bit. I'm monkeying with parameters right now trying to figure out what causes what.

Can anyone explain what value-add there is in the gulp-sourcemaps and vinyl-apply-sourcemaps plugins? If node-sass generates decent sourcemaps on its own (as I believe it does, at least in v2), then what are they doing for us? I ask this innocently, not as a rhetorical question.

**Comment by aaronjensen** [comment]
Well, I know I use `gulp-sourcemaps` in order to deal w/ source maps across sass, autoprefixer and concat:

```js
gulp.task('css', ->
  vendor = gulp.src([
    'node_modules/normalize.css/normalize.css'
  ])

  main = gulp.src(['app/assets/css/main.sass'])
    .pipe(plumbing(errorTitle: "Sass Error"))

    .pipe(env.ifDevelopment sourcemaps.init())
    .pipe(sass(indentedSyntax: true))
    .pipe(env.ifDevelopment sourcemaps.write(sourceRoot: '/'))

    .pipe(env.ifDevelopment sourcemaps.init(loadMaps: true))
    .pipe(autoprefixer())
    .pipe(env.ifDevelopment sourcemaps.write(sourceRoot: '/'))

  merge(vendor, main)
    .pipe(env.ifDevelopment sourcemaps.init(loadMaps: true))
    .pipe(concat("main.css"))
    .pipe(env.ifDevelopment sourcemaps.write('./'))

    .pipe(env.ifProduction minify())
    .pipe(env.ifProduction rev())

    .pipe(gulp.dest('public/css'))
    .pipe(filter('**/*.css'))
    .pipe(reload(stream: true))

    .pipe(env.ifProduction rev.manifest(path: 'manifest.json'))
    .pipe(env.ifProduction gulp.dest('public/css'))
)
```

**Comment by laurelnaiad** [comment]
Gotcha. Thanks.

I'm going to keep hammering on this a bit for a few minutes, It seems like I may be *required* to enable sourceComments in order to get sourcemaps generated, and I don't think this should really be necessary, so I'm not thrilled with my current situation.

The Steelers are coming on, though, so I need to get to that soon. :)

**Comment by aaronjensen** [comment]
Yes, that’s how it was before. I don’t know why exactly either, but it was required previously.


Aaron

**Comment by laurelnaiad** [comment]
Commercial break. I think I'm making progress. I'm converting from a map-stream to an even-stream so I can add the sourcemap file manually. I think this may be part of the key to overcoming the need for sourceComments (I suspect their absence may be incompatible with the vinyl-apply-sourcemaps feature, or something like that).

Nothing certain yet, it's all still a bit murky given the various parameter combinations.

**Comment by dlmanning** [comment]
@laurelnaiad Thanks for all the work you're putting into figuring out node-sass 2.0. I haven't looked into it very much yet. If you could put a link to your branch/fork in this thread I'd love to see what you're doing.

**Comment by laurelnaiad** [comment]
Thanks, @dlmanning. My code is in flux atm. I will get it to a reasonably
steady state tonight and push what I have.
