### ISSUE TITLE
@import fails with invalid property error

### ISSUE THREAD

**Issue by kristoferjoseph** [dlmanning/gulp-sass#169]
Using import with gulp-sass fails with 
`Error: invalid property name`
This is not a very useful error so I attached an example project to help debug.
https://github.com/kristoferjoseph/gulp-sass-import-fail
https://github.com/kristoferjoseph/gulp-sass-import-fail/archive/1.0.zip
Add any property to the `.button` class and the error persists unchanged.

Seems like this should work fine. Any idea what is going on?

**Comment by aaronjensen** [comment]
I assume you added the semi-colon, which is invalid in indented sass because it gave you this error:
`Error: top-level @import directive must be terminated by ';'`

gulp-sass apparently has a hard time with top level indented syntax (`.sass`) files. If you rename your file to `.scss` it'll work, but gulp-sass and node-sass should be able to handle indented syntax on the top level. This is a regression, though in order for it to work prior to 1.3, you had to specify `sourceComments: 'normal'` or it wouldn't work with indented syntax.

**Comment by kristoferjoseph** [comment]
Interesting.
I changed the file names to `.scss` and they work as expected. Somewhat annoying, but I am ok with it.
@aaronjensen Thanks for the help I appreciate your time bud. :+1:
