### ISSUE TITLE
Add New Collaborators

### ISSUE THREAD

**Issue by dlmanning** [dlmanning/gulp-sass#213]
I've gotten really busy lately and haven't been able to keep up with issues as well as I ought. Is anyone interested in being a collaborator for this project? Reply in this thread or email me if so.

**Comment by shinnn** [comment]
:hand: I can take it on.

I'm maintaining a lot of gulp plugins whose owners are too busy to maintain them:

* hparra/gulp-rename#35
* adamayres/gulp-wrap#16
* adametry/gulp-eslint#24
* https://github.com/lmtm/gulp-front-matter/pull/5#issuecomment-65747363
* kombucha/gulp-assets#8
* kombucha/gulp-assets#8
* shinnn/gulp-gh-pages#50

**Comment by Snugug** [comment]
@dlmanning When I'm back at my desk next week I'd be happy to help.

**Comment by Keats** [comment]
Hey I made a PR to make gulp-sass work with node-sass 3.0 (https://github.com/dlmanning/gulp-sass/pull/207) but it should probably not be merged since it's still in alpha-beta.

I was thinking of writing a gulp-sass 2.0 to solve some of the open issues and maybe do some breaking changes (like removing the callbacks, unless someone has a valid usecase for those), I'll post a link to it once I've done it

**Comment by dlmanning** [comment]
@Keats : Were you also wanting to be added as a collaborator then?

**Comment by Keats** [comment]
I can help yes

**Comment by dlmanning** [comment]
@Keats @Snugug I've added you both as collaborators. Feel free to fix what needs fixing, though I'd like to at least LGTM any complete rewrite. Thanks for your help!

**Comment by Snugug** [comment]
@Keats I couldn't find you in the list of people to invite. We've got a [Gitter set up to chat](https://gitter.im/dlmanning/gulp-sass)
