### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by TheDutchCoder** [dlmanning/gulp-sass#297]
An issue for this already existed but is closed and there's no response to the people that still experience this.

This still happens for me on Windows 7 on the main file I'm watching.

It's a real nuisance, as it sometimes take about 10 tries (saves) to get the file to compile!

**Comment by Snugug** [comment]
That issue was closed because the community had found a working fix. We've adopted their fix as the [suggested answer](https://github.com/dlmanning/gulp-sass/wiki/Common-Issues-and-Their-Fixes#partials-sporadically-not-found). Please do not open duplicate issues, instead comment on the existing issue.
