### ISSUE TITLE
Variable Name Error

### ISSUE THREAD

**Issue by jonorherrington** [dlmanning/gulp-sass#318]
When running gulp sass, whenever I have a variable name that has a _ in it, it shows it as an -.

For instance, say I have an undefined variable named $form-input__color. When an undefined variable error comes up it shows it as Undefined error: "$form-input--color". 

I spent 30 minutes this morning trying to find this said undefined variable, only to find that this bug was in the task. 

Any ideas how to fix this?

**Comment by Snugug** [comment]
This is an issue with libsass, please [repost your question there](https://github.com/sass/libsass/issues).

I predict the reason it's happening is because `-` and `_` are actually [interchangeable in Sass](http://sassmeister.com/gist/2e94af0fea1039ce1cb9) and Libsass is probably doing that conversion when it's reading the Sass file and, if there's an issue, printing out the converted version instead of the original one.
