### ISSUE TITLE
gulp-sass inserts byte order mark EF BB BF in output

### ISSUE THREAD

**Issue by doginthehat** [dlmanning/gulp-sass#348]
I've been getting this odd issue where Chrome ignores some of my @font-face declaration.

After checking the output, I've noticed an odd character preceding the declaration, which a hex editor revealed to be EFBBBF (byte order mark).

It is only apparent because i'm piping the output with gulp-header.

My build task is like this:

```
gulp.task('sass-style', function () {
  return gulp
    .src('scss/build.scss')
    .pipe(sass({outputStyle: 'compressed'}).on('error', function(err) {notify().write(err); this.emit('end');}))
    .pipe(rename('style.css'))
    .pipe(header('/*! <%= name %> - <%= version %> - <%= author %>  <%= (new Date()).getFullYear() %> */',pkg ))
    .pipe(gulp.dest('build/'))
    .pipe(browserSync.stream())
  ;
});
```

The BOM gets placed right after the header, but it isn't inserted by gulp-header itself, which just concatenates the header with the piped output.

I've tried to remove some of the stream handler to make sure they're not the culprit.

```
gulp.task('sass-style', function () {
  return gulp
    .src('scss/build.scss')
    .pipe(sass({outputStyle: 'compressed'}).on('error', function(err) {notify().write(err); this.emit('end');}))
    .pipe(gulp.dest('build/'))
    .pipe(browserSync.stream())
  ;
});
```

And checked the out with Text Wrangler (osx) and it confirms that a BOM is added.

![screen shot 2015-09-23 at 14 38 18](https://cloud.githubusercontent.com/assets/843366/10037973/d781b462-6200-11e5-8930-7327b7f211cd.png)

Unless i'm missing something in my build script, there seems to be an BOM incorrectly inserted in the output.

(There was a vague mentioned of the BOM in this other issue https://github.com/dlmanning/gulp-sass/issues/82 which said it was marked as fixed in the 2.x branch, but I'm on the latest – 2.0.4 – and it's happening)

I've got the following gulp packages in my build setup:

```
    "gulp": "^3.9.0",
    "gulp-concat": "^2.6.0",
    "gulp-footer": "^1.0.5",
    "gulp-header": "^1.2.2",
    "gulp-notify": "^2.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.0.4",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.6",
    "gulp-webpack": "^1.5.0",
```

Happy to test further if you have any suggestions.

**Comment by xzyfer** [comment]
Thanks for the report @doginthehat. Could you please created a small GitHub repo with a minimal wotk example reproducing this issue. This will do will help us collaborate with the node-sass and libsass teams to get to the bottom of the issue. It will also ensure there are no other external factors. In our experience the process of creating these test repos in itself surfaces the problem.

**Comment by doginthehat** [comment]
Hi @xzyfer 

Thanks for getting back to me. 

I took your advice and setup a bare bone test repository to replicate the issue and as you thought, I couldn't reproduce the error then.

*But*

I then went back to the faulty project and tried to prune down chunks of the sass source files to try to narrow it down to what was causing the issue in that specific project.

And I did narrow it down to one specific line of sass, from Font Awesome's source scss files.

Here's the test repo: <https://github.com/doginthehat/gulp-sass-bug-test>

If you checkout commit 687cdcc and run gulp, this has some lines of codes from font awesome that trigger the BOM creation.

If you checkout commit 87d4534 (the current head)  and run gulp, I'm modified one line of code and it doesn't trigger the BOM creation.

Specifically, it seems that the unicode string `"\f000"` triggers the BOM creation.

According to Font Awesome's source, that code is from the *Unicode Private Use Area (PUA)*.

So, there's the info :smile: 

Not sure if that's a gulp-sass, node-sass, libsass, or event font awesome bug.

Let me know if I can be of further help.

**Comment by doginthehat** [comment]
Additional info (if it's any use)

```
# node --version
v4.1.1
# npm --version
3.3.4
```

**Comment by doginthehat** [comment]
Interestingly, I've tried gulp-header again and it's now stripping the BOM header in the concatenation ok.

(I did update node to the latest version since the initial bug report, can't remember which version it was).

If you checkout commit 4bfa60c and run gulp, gulp-header will successfully remove the BOM before concatenating, which solves the initial issue I had. 

Still leaves the actual BOM bug from `\f000`

**Comment by xzyfer** [comment]
Thanks @doginthehat this is perfect! I'll get to this when I have a moment.

**Comment by xzyfer** [comment]
@doginthehat I didn't previously understand this issue.

This problem has been filled a handful times. LibSass is creating the output. Ruby Sass produces the same output. The output CSS may look strange but the browsers interpret it correctly because the `@charset "UTF-8";` which LibSass adds.

Interestingly in compressed mode the `@charset` isn't being generated which could be why Chrome is unhappy.

**Comment by spiritix** [comment]
I can confirm this bug - any updates? For us it breaks our CSS.

**Comment by shockthetoast** [comment]
We're having the exact same issue. None of the source files use BOM, but these get added on output, and then when the files are concatenated BOMs end up in the middle of the file. This sometimes caused Chrome to break the display of icon fonts.

I seem to have tracked it down to use of unicode characters in the CSS. Our icons are being specified in psuedo-classes likes so: `content: "\F43E"`. The output from gulp-sass replaced those identifiers with the actual unicode character, so it appears something like `content:""`. (This is a character from the private use area of Unicode.) Every file that had an icon in a content property had the BOM added. Every file that didn't have an icon/unicode character didn't get the BOM.

This seems to have resulted in Chrome being confused about the encoding. Sometimes (especially on a slow connection) it will show gibberish. I believe Chrome has to read a certain amount of the file before it figures out what's going on with the encoding, but when the load is slow it doesn't read enough before it makes its guess.

I have currently solved the problem by using two tools - one that reverts the unicode characters back to their code point identifier (`"\F43E"`) and one that strips out BOM characters. By piping to both of these before piping to gulp-concat the issue is resolved.

**Comment by kapooostin** [comment]
@shockthetoast How exactly do you strip out BOM characters?

**Comment by shockthetoast** [comment]
@kapooostin I run the output from gulp-sass through _gulp-sass-unicode_ (which converts unicode characters into their escape sequences) and then _gulp-stripbom_ to remove the BOM.

**Comment by kapooostin** [comment]
@shockthetoast Thanks a lot!

**Comment by shockthetoast** [comment]
> Interestingly in compressed mode the `@charset` isn't being generated which could be why Chrome is unhappy.

@doginthehat, it turns out that in compressed mode, sass uses the BOM instead of @charset rule because... it's shorter. https://github.com/sass/sass/issues/1449

The Unicode Guidelines state that using the BOM is allowed in utf-8, but *not* recommended.
(Source: [this Stack Overflow answer](https://stackoverflow.com/a/2223926) which links to the official docs.)

The concatenation issue is one reason it's a terrible idea. I love saving space as much as the next guy, but I don't feel the savings sixteen characters is worth it. From the 17 characters of `@charset "UTF-8";` to the  one BOM character.

Of course, this being done by sass itself, and not gulp-sass, so it can't be fixed here. But hopefully this information is helpful to someone.

**Comment by XhmikosR** [comment]
@xzyfer this is also unrelated to gulp-sass itself.
