### ISSUE TITLE
Is there any news about css-files @import?

### ISSUE THREAD

**Issue by artem-malko** [dlmanning/gulp-sass#362]

**Comment by xzyfer** [comment]
Please be more specific.

FYI this feature may be removed from LibSass in the near future because if differs from Ruby Sass' behaviour.

**Comment by artem-malko** [comment]
I just would like to import css files like scss(sass). So, is there any idea, how can i do it, without original css-files renaming?

**Comment by xzyfer** [comment]
If you're using the latest node-sass this should work fine. However this may stop working in the future so I wouldn't rely on it.

**Comment by artem-malko** [comment]
@xzyfer so, what is the decision for css-import? How can I do it?

**Comment by xzyfer** [comment]
If you `@import` a `.css` file it will be inlined into the file. It has been this way for a long time.

Should you do it. No.

**Comment by artem-malko** [comment]
@xzyfer ok, I understood it. But what should I do with all my css-files?

**Comment by xzyfer** [comment]
The right thing to do is rename them all to `.scss`. I can't imagine a reason not to do this.

If you really don't want to it's fine, gulp-sass will compile `.css` files like they're `.scss`. We don't look at the file name because gulp works on data streams, not files. You're going to run into issues though if you `@import` as `.css` because doesn't recognise this as a Sass file.
