### ISSUE TITLE
`libsass` bindings not found in error

### ISSUE THREAD

**Issue by IntellectProductions** [dlmanning/gulp-sass#387]
So my gulp was running smoothly about a month ago until I tried to run it today..
This is my package.json file to show all my dependencies I have installed:

```js
{
  "name": "CMS",
  "version": "0.0.0",
  "description": "Node dependencies for Ventrac\\CMS",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Haley Schillig",
  "license": "ISC",
  "devDependencies": {
    "bootstrap": "^3.3.5",
    "bootstrap-sass": "^3.3.5",
    "font-awesome": "^4.4.0",
    "form-serialize": "^0.6.0",
    "gulp-sass": "^2.1.0",
    "jquery": "^2.1.4",
    "node-sass": "^3.4.1",
    "tinymce": "^4.2.6",
    "vue": "^0.12.16",
    "vue-resource": "^0.1.16"
  }
}
```

I went through this page: https://github.com/dlmanning/gulp-sass/issues/174 And tried all their fixes. I uninstalled gulp-sass and node-sass and reinstalled both. I tried to remove node-sass from gulp-sass node_modules. I removed node_modules and ran npm install again. I tried to clear npm cache... nothing is working.

Thanks for any help.

Node version - 4.2.1
NPM version - 2.4.17
OS - Windows 8.1 (win32 64 bit)

EDIT::
I tried all these solutions too : http://stackoverflow.com/questions/28409100/try-reinstalling-node-sass-on-node-0-12

**Comment by JuanHB** [comment]
I'm having the same issue here, but I'm trying to install the last version and getting 404 error for this file: 
``` 
https://github.com/sass/node-sass/releases/download/v3.4.1/win32-x64-47_binding.node 
```
If you go to the releases directory in the node-sass repo, you will see that in fact the ```win32-x64-47_binding.node``` file doesn't exists there, only the earlier version: ```win32-x64-46_binding.node```

**Comment by xzyfer** [comment]
@JuanHB this is not related has been answered many times. We do not yet support Node 4 on Windows because the service we use to generate the native code hasn't been updated it. If you're using a node version that's a week old you can expect things not to work. Down grade your node and everything will be fine.

**Comment by xzyfer** [comment]
@IntellectProductions this error means only one thing, node-sass wasn't installed correctly. This generally happens when you OS (i.e. in a vm) or version of Node. Removing node_modules **always** fixes the problem. If the problem persists it's because the version of node you're npm installing with is not the version of node you're executing the code with.

I cannot assist any further as this is an environmental issue. Make sure all the places you're interacting with node-sass you are using the same version of node. You can always run `npm rebuild` to rebuild the node-sass binary for your new environment.
