### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`

### ISSUE THREAD

**Issue by fangge** [dlmanning/gulp-sass#414]
this problem show again.
node - v5.1.0
npm -v3.3.12
I install gulp-sass 1.3.3
And the error just show again~No idea why it happened

**Comment by caleuanhopkins** [comment]
have this same issue on node - v4.2.3

**Comment by caleuanhopkins** [comment]
@fangge checkout [this comment](https://github.com/sass/node-sass/issues/1247#issuecomment-154285934).

run `npm ls node-sass` in your terminal and check to see how many version of `node-sass` are returned. In my case, `grunt-iconify` was still on v0.1.0 and was loading an old version of `node-sass` causing my issue.  Removing `grunt-iconify` and updating it to latest version of v0.4.0 fixed this issue for me. Check in case another package has a dependence to an older version of `node-sass` which causes the `libsass` error

**Comment by xzyfer** [comment]
This error means that the environment you ran npm install on, is different to the environment you're running your node code on. Native extension like node-sass need to be compiled against a specific combination of node version, os, and 32/64bit. If of that changes the extensions need to be compiled (re-installed).

This error usually happens because you've upgraded node or run npm install on a virtual machine with a shared filesystem (i.e docker). Either way the solution is always to run `npm rebuild node-sass`.
