### ISSUE TITLE
Gulp 4: increases compile time on each save

### ISSUE THREAD

**Issue by pelllich** [dlmanning/gulp-sass#467]
While gulp watch for changes, compile time increased with every save, even if the styles do not change much.

Running on `Windows 7x64`, `gulp v4`, `gulp-sass v2.2.0`

Gulp task to compile sass:
```javascript
function compileSass() {
  return gulp.src(srcDir + 'scss/app.scss')
    .pipe(plugins.plumber({
      errorHandler: onError
    }))

    // globbing CSS @import
    .pipe(plugins.sassBulkImport())

    .pipe(plugins.sass({
      sourceMapContents: true,
      sourceMapEmbed: true
    }))
    .pipe(gulp.dest(srcDir + 'css/'))
    .pipe(browserSync.reload({stream: true}));
}
```

![untitled-1](https://cloud.githubusercontent.com/assets/2727342/14690891/0aea21a8-0757-11e6-984a-dd5529e309df.png)

**Comment by xzyfer** [comment]
Does it actually get slower of does the number just increase. I gulp-sass every day and have never seen this.

**Comment by xzyfer** [comment]
Try disabling your sourcemap settings and see if the problem persists.

**Comment by pelllich** [comment]
It is really get slower. When i am using `gulp v3` it works nice. 
Tried to disable sourcemap, but the problem still exist.

**Comment by xzyfer** [comment]
Interesting. I don't currently use gulp 4 so I'm not sure what's happening.

**Comment by alexbikazzan** [comment]
I've been having the same issue for quite some time, after a while it gets really slow. My guess is that they problem is with the watch itself, because when I restart the watch the compile time goes down again.

![image](https://cloud.githubusercontent.com/assets/3288453/15243142/2fa3fe92-18fa-11e6-8174-4e7b19733b34.png)

**Comment by xzyfer** [comment]
I believe this probably related to #509.

**Comment by xzyfer** [comment]
I expect this might be fixed with v2.3.2. Please let me know if that is not the case.

**Comment by thasmo** [comment]
@xzyfer I've the same problem since quite some time with Gulp v4 but didn't actually look it up until now. It's definitely `gulp-sass` and the issue still exists with version 2.3.2 when using Gulp v4. I've tried to reproduce the same issue with other gulp plugins, but only `gulp-sass` shows the behavior of each iteration taking longer than the previous one.

First I thought it's maybe sourcemaps or plumber or autoperfixer, but the problem seems to exist within `gulp-sass`.

Currently the only way to work with `gulp-sass` is to kill the watch task now and then, because otherwise the watch task gets really slow over time.

**Comment by bonjurmrfirst** [comment]
Try something like:
`gulp.task('styles', function() {
  let tempSass = require('gulp-sass');

  return gulp.src(SRC)
    .pipe(tempSass().on('error', plugins.sass.logError))
    ...
`

**Comment by tusbar** [comment]
I am still getting this with `gulp-sass@3.1.0`.

```
[15:01:40] Finished 'styles' after 7.36 s
[15:02:20] Starting 'styles'...
[15:02:27] Finished 'styles' after 6.91 s
[15:02:37] Starting 'styles'...
[15:02:44] Finished 'styles' after 7.24 s
[15:02:54] Starting 'styles'...
[15:03:02] Finished 'styles' after 8.09 s
[15:03:31] Starting 'styles'...
[15:03:39] Finished 'styles' after 7.4 s
[15:04:34] Starting 'styles'...
[15:04:42] Finished 'styles' after 8.36 s
[15:05:03] Starting 'styles'...
[15:05:11] Finished 'styles' after 8.2 s
[15:05:13] Starting 'styles'...
[15:05:22] Finished 'styles' after 8.35 s
[15:05:36] Starting 'styles'...
[15:05:44] Finished 'styles' after 8.35 s
[15:06:28] Starting 'styles'...
[15:06:36] Finished 'styles' after 8.46 s
[15:08:35] Starting 'styles'...
[15:08:45] Finished 'styles' after 9.29 s
[15:10:06] Starting 'styles'...
[15:10:15] Finished 'styles' after 9.16 s
[15:11:15] Starting 'styles'...
[15:11:24] Finished 'styles' after 9.02 s
```

**Comment by nicothin** [comment]
+1

This problem occurs not only when compiling SASS. I watch it from Gulp 4 and when compiling Pug. 
(In a completely identical repository from Gulp 3, I do not observe such a problem.)
Win10.

Apparently, the authors of the Gulp 4 are more comfortable not to get this problem :( https://github.com/gulpjs/gulp/issues/1748
This is the opensource, baby! )))

ps: the problem can be solved if you avoid using `**/` in the `gulp.watch`. To write not `**/*.scss`, and to specify more precisely: `yourDirectory/*.scss`
This solution is not convenient, but I have not found another yet.

**Comment by lukasradek** [comment]
I am still experiencing this.
