### ISSUE TITLE
Change node-sass dependency

### ISSUE THREAD

**Issue by basvandenheuvel** [dlmanning/gulp-sass#472]
Right now, everybody using gulp-sass has big big problems when they are behind a proxy because the new node-sass version has issues.

Please release a version of gulp-sass that refers to a static version of node-sass and do not use the "^" in front of it. It's bad practice and dangerous as you can see right now.

**Comment by xzyfer** [comment]
Thank you, as already explained we are aware of the issue and will prioritize a fix in node-sass.

**Comment by jhnsnc** [comment]
I think we should consider re-opening this issue in order to discuss the version of `node-sass` required by this package. The caret version range exposes us to a lot of risk since I can't even fall back to using an older version of `gulp-sass`--they all end up pulling in the problematic version of `node-sass`.

I would support swapping to a [more conservative version range](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1) for the `node-sass` dependency.
