### ISSUE TITLE
Getting incorrect path with sourcemaps, am I doing something wrong?

### ISSUE THREAD

**Issue by MattHoneycutt** [dlmanning/gulp-sass#498]
I'm very new to this package, so it's quite possible I'm doing something wrong or that it isn't a gulp-sass issue.  Any help, or a nudge in the right direction, is greatly appreciated. :) 

That said: 

I'm using gulp-sass with bootstrap-sass.  I'm starting with a simple SCSS file, vendor.scss:

``` scss
@import "../../../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
@import "custom.scss";
```

My custom.scss:

``` scss
body {
    background-color: pink;
}
```

And my gulp task:

``` js
gulp.task('css:vendor', function() {
    return gulp.src('./client/features/shared/vendor.scss')
        .pipe(sourcemaps.init())
        .pipe(sass({ outputStyle: 'compressed', sourceComments: 'map' }))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./dist'));
});
```

Everything builds, the resulting CSS is what I would expect, but the sourcemap is off for the style from my custom.scss.  It seems to be "stuck" on the last file that was processed from bootstrap's package:

![image](https://cloud.githubusercontent.com/assets/156878/15409951/dee1aa12-1ddc-11e6-8946-d98613d3d7bb.png)

Any tips or suggestions?

**Comment by MattHoneycutt** [comment]
I've tried a few different configurations of things, but I'm still getting the same behavior.  Any advice?

**Comment by zephster** [comment]
Have you tried using `outputStyle: 'compact'` instead of `compressed`? I have the same issue when I use `compressed`, but changing it to `compact` fixes it. I haven't found a proper solution for this issue, because I would prefer to use `compressed`.

**Comment by antwan1986** [comment]
Yep my fix is the same, had to use `compact`. No idea why this works.

**Comment by Sash-OK** [comment]
the problem has not been solved? When i use `autoprefixer` ,`outputStyle: compact` does not help, Chrome DevTools shows that all children are on a parent line in the file SCSS

**Comment by MattHoneycutt** [comment]
outputStyle: compact doesn't work for me, either. :(

**Comment by luketeaford** [comment]
@Sash-OK If you are running autoprefixer on your outputted Scss, I would expect it to break the associations between rules and the source maps.

**Comment by MattHoneycutt** [comment]
I'm seeing it break even without autoprefixer, using outputStyle: compact.  That doesn't mean autoprefixer isn't breaking things, too, but it isn't the culprit in my case.

**Comment by luketeaford** [comment]
@MattHoneycutt I think you should change 
` .pipe(sass({ outputStyle: 'compressed', sourceComments: 'map' }))`

to

` .pipe(sass({ outputStyle: 'compressed'}))` or `.pipe(sass())`

I haven't payed close attention to Gulp Sass, but now I notice that sourcemaps are a different plugin rather than an option of Gulp Sass. (If this doesn't work, perhaps calling `sourcemaps(write())` will fix it?)

**Comment by Dellkan** [comment]
Also having this issue. Using `{outputStyle: 'compact'}` instead of `{outputStyle: 'compressed'}` gives me correct sourceMaps.

**Comment by JoshMoreno** [comment]
Still waiting for a fix.

@Dellkan , @MattHoneycutt - The first problem is bootstrap _breadcrumbs.scss. I opened an issue over there - https://github.com/twbs/bootstrap-sass/issues/1105

Their variable interpolation value in `_breadcrumbs.scss` causes libsass to:

1. not compile correctly (don't worry it's just messes up that one line)
2. mess up sourcemaps when the output style is set to `compressed`

After you fix that issue, it appears that there is something gulp-sass has to fix because node-sass compiles everything fine (after fixing bootstrap issue) when running `--output-style compressed --source-map true`. I'm trying to come up with a temporary solution, that doesn't involve using a different tool to minify so we can keep the speed gains from libsass, until the issues are resolved.

**Comment by JoshMoreno** [comment]
@Dellkan @MattHoneycutt I think I spoke too soon. I don't think it's a problem with gulp-sass anymore. I still had postcss running autoprefixer in the stream. When I commented that out and just ran gulp-sass with sourcemaps and `outputStyle: 'compressed'` it's working fine.

So it seems like the problem is postcss or autoprefixer. Will update as I find out more. The bootstrap breadcrumbs issue still holds true though as it messes up libsass itself.

**Comment by chris-sparks** [comment]
I can confirm that simply commenting out the:
`.pipe(autoprefixer())`
Solved my issues with Sourcemaps incorrectly reporting files/line numbers. I'm not using BS in this instance.

**Comment by xzyfer** [comment]
This is either an issue with libsass (used by gulp-sass), or another gulp plugin interfering. 

Comment out all other gulp-plugins. If the issue persists open an issue with libsass.

**Comment by bonovski** [comment]
Ok, so, when I use compact the sourcemaps are OK, with compressed gulp-sourcemaps references the wrong/random files. 
Are there any fixes for this?
```
gulp.task( 'styles', function() {
	gulp.src( [ styleSRC ] )
		.pipe( sourcemaps.init() )
		.pipe( sass({
			includePaths: [ foundation, motionUI, datepicker ],
			errLogToConsole: true,
			outputStyle: 'compact'
		}) )
		.on( 'error', notify.onError( function (error) {
			return 'An error occurred while compiling sass.\nLook in the console for details.\n' + error;
		} ) )
		.pipe( autoprefixer({ browsers: [ 'last 2 versions', '> 5%', 'Firefox ESR' ] }) )
		.pipe( rename( { suffix: '.min' } ) )
		.pipe( sourcemaps.write( mapURL ) )
		.pipe( gulp.dest( styleURL ) )
		.pipe( browserSync.stream() );
});

```

**Comment by andywarren** [comment]
Just wanted to add to this as well. I also have the issue with sourcemaps not matching up correctly, and can also confirm it is strictly happening when the `outputStyle: 'compressed'` option is passed in. When changing it to `outputStyle: 'compact'` the sourcemaps again match up correctly. I'd really like to be able to have the stylesheet completely minified though.

**Comment by JoshMoreno** [comment]
For anyone digging around, the issue isn't with gulp-sass.

It's a known issue. Libsass (maybe node sass) seems to still have a bug - https://github.com/sass/node-sass/issues/957

Also, PostCSS isn't fully compatible with sass sourcemaps and the issue has been closed as won't fix (though he tried 👍) - https://github.com/postcss/postcss/issues/926
