### ISSUE TITLE
Move `node-sass` to optional or peer dependancy

### ISSUE THREAD

**Issue by simon-tma** [dlmanning/gulp-sass#714]
Now that using Dart Sass is documented, it'll be nice to be able to not install node-sass.

**Comment by xzyfer** [comment]
This has been discussed and is not on the road map for the time being.

**Comment by xzyfer** [comment]
You can look at gulp-dart-sass for the time being

**Comment by Kocal** [comment]
Weird, since we can use node-sass or dart-sass I don't understand why we are forced to have node-sass to be always installed.

It's even documented in the README :confused:
> # Install
> `npm install node-sass gulp-sass --save-dev` 

If we have to install node-sass ourselves, then it should be marked as a peer dependency, not a direct dependency. :thinking:
