### ISSUE TITLE
Update node-sass to 4.12.0 for NodeJS 12 support and to reverse a noisy CSS import deprecation warning

### ISSUE THREAD

**Issue by simonua** [dlmanning/gulp-sass#719]
Please update node-sass to [4.11.0](https://github.com/sass/node-sass/releases). That version is currently in pre-release while 4.10.0 is `latest`, so I expect this issue to hang around for a bit. I'll have a small PR for this shortly.

**Comment by simonua** [comment]
At some point in the last three months, node-sass@4.11.0 has been promoted from _beta_ to _latest_. @dlmanning, would you be able to review the associated PR, please? Thank you!

**Comment by simonua** [comment]
I updated the associated PR with the latest version of node-sass released a few days ago that now supports NodeJS 12. @dlmanning, would be really, really great if this could be merged and released. Pretty please.

**Comment by simonua** [comment]
Updating node-sass to 4.12.0 does the trick as a work-around until this PR is merged.

**Comment by xzyfer** [comment]
This is not needed because of how SemVer works. You can always update the transient node-sass with `npm update node-sass` if you wish.

https://nodesource.com/blog/semver-tilde-and-caret

**Comment by htkoca** [comment]
It would allow `gulp-sass`, amongst other changes in `node-sass > 4.8.3`, to finally be able to import `.css` files. 

Currently the `@import` statements that contain `.css` file references end up in the built file as `@import url ('path/to/example.css')` instead of having their contents copied into the built file. I think it would be great to have this out of the box for `gulp-sass`.
